services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: gym
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports: ["5432:5432"]
    volumes:
      - pg:/var/lib/postgresql/data
      - ./db-seed:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gym"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    image: demo:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75"
    ports: ["8080:8080"]

volumes:
  pg: